### ISSUE TITLE
LinuxGSM and Is my gameserver online

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/awesome#1]
LinuxGSM and https://ismygameserver.online/

**Comment by CosminPerRam** [comment]
You madlad, didn't even had the time to push the guidelines on adding a project (:

**Comment by dgibbs64** [comment]
It popped up on my feed so I thought why not 😄

**Comment by CosminPerRam** [comment]
Added the main files, feel free to also add your website and modify the LinuxGSM entry if you want to
